# Generated by Django 3.1 on 2020-08-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200816_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Saiu para entrega', 'Saiu para entrega'), ('Entregue', 'Entregue')], max_length=200, null=True),
        ),
    ]
