# Generated by Django 3.1 on 2020-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200818_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Saiu para entrega', 'Saiu para entrega'), ('Entregue', 'Entregue')], max_length=100, null=True),
        ),
    ]
