# Generated by Django 3.1.1 on 2020-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_auto_20200921_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='obs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
