# Generated by Django 3.1.1 on 2020-09-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0004_auto_20200922_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='cnpj',
            field=models.CharField(blank=True, default=' ', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='obs',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='telefone',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
